### ISSUE TITLE
Improvements to existing html pages

### ISSUE THREAD

**Issue by MansiAyer** [MansiAyer/TE#9]
html pages in WDL need some improvements to make the output look better, most pages contain very basic formatting and css that were only to temporarily get the submission done.

**Comment by aryanthakre** [comment]
Assign Me !!

**Comment by LINSMARIYA** [comment]
Assign me to do it.

**Comment by MansiAyer** [comment]
@aryanthakre @LINSMARIYA hey guys, sorry it took me a while to get back to you. Are you both still interested to do it?

**Comment by aryanthakre** [comment]
@MansiAyer Yes why not until you give a hacktoberfest-accepted label.

**Comment by aryanthakre** [comment]
Assign Me !!

**Comment by LINSMARIYA** [comment]
> @aryanthakre @LINSMARIYA hey guys, sorry it took me a while to get back to you. Are you both still interested to do it?

Yes

**Comment by MansiAyer** [comment]
`this isn't a hacktoberfest repo, issue is being closed`
